---
title: "Understanding study `r params$study` at `r params$ld_block`"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  prettydoc::html_pretty:
    theme: cayman
    css: ../pipeline_steps/pipeline_summary.css
---

```{r setup, include=FALSE} 
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
```

```{r echo=F}
source('../pipeline_steps/constants.R')
manhattan <- function(gwas, title) {
  manhattan_columns <- c("SNP", "CHR", "BP", "P")

  gwas$P[gwas$P == 0] <- .Machine$double.xmin
  x_range <- c(min(gwas$BP), max(gwas$BP))

  qqman::manhattan(gwas, xlim = x_range, main = title, cex.main = 0.7)
}

ld_info <- ld_block_dirs(params$ld_block)
extracted_study <- vroom::vroom(glue::glue('{ld_info$ld_block_data}/extracted_studies.tsv'), show_col_types=F) |>
  dplyr::filter(study == params$study)
extracted_gwas <- vroom::vroom(extracted_study$file, show_col_types=F)

standardised_study <- vroom::vroom(glue::glue('{ld_info$ld_block_data}/standardised_studies.tsv'), show_col_types=F) |>
  dplyr::filter(study == params$study)
standardised_gwas <- vroom::vroom(standardised_study$file, show_col_types=F)

imputed_study <- vroom::vroom(glue::glue('{ld_info$ld_block_data}/imputed_studies.tsv'), show_col_types=F) |>
  dplyr::filter(study == params$study)
imputed_gwas <- vroom::vroom(imputed_study$file, show_col_types=F)

finemapped_studies <- vroom::vroom(glue::glue('{ld_info$ld_block_data}/finemapped_studies.tsv'), show_col_types=F) |>
  dplyr::filter(study == params$study)

finemap_info <- head(finemapped_studies, 1)
finemapped_gwases <- lapply(finemapped_studies$file, function(file) {
  vroom::vroom(file, show_col_types=F)
})
mean_finemap_size <- lapply(finemapped_gwases, function(gwas) nrow(gwas))
```

GWAS Study size per step
```{r echo=F}

sizes <- data.frame(extracted=nrow(extracted_gwas), standardised=nrow(standardised_gwas), imputed=nrow(imputed_gwas))
knitr::kable(sizes)
```

## Standardised GWAS

```{r echo=F}
manhattan(standardised_gwas, glue::glue("Standardised GWAS of {params$study}"))
```

## Imputed GWAS

```{r echo=F}
manhattan(imputed_gwas, glue::glue("Imputed GWAS of {params$study}"))
```

## Finemapped GWASes

* First finemap, number of results: `r finemap_info$first_finemap_num_results`
* QC Step run: `r finemap_info$qc_step_run`
* Second finemap, number of results: `r finemap_info$second_finemap_num_results`
* SNPs removed by QC: `r finemap_info$snps_removed_by_qc`
* Variant type: `r finemap_info$variant_type`

```{r echo=F}
dont_print <- apply(finemapped_studies, 1, function(study) {
  gwas <- vroom::vroom(study["file"], show_col_types=F)
  manhattan(gwas, glue::glue('Finemapped GWAS of {study["unique_study_id"]}'))
})
```