import os
import numpy as np
import pandas as pd
import subprocess

DATA_DIR = os.getenv('DATA_DIR')
RESULTS_DIR = os.getenv('RESULTS_DIR')
TIMESTAMP = os.getenv('TIMESTAMP')
PIPELINE_METADATA = DATA_DIR + 'pipeline_metadata/'
STUDY_DIR = DATA_DIR + 'study/'
LD_BLOCK_DATA_DIR = DATA_DIR + 'ld_blocks/'
LD_BLOCK_MATRICES_DIR = DATA_DIR + 'ld_block_matrices/'
LD_BLOCK_RESULTS_DIR = RESULTS_DIR + 'ld_blocks/'

### INPUT DATA FILES
studies_to_process_file = PIPELINE_METADATA + 'studies_to_process.tsv'
studies_to_process = pd.read_csv(studies_to_process_file , sep='\t')

ld_regions = pd.read_csv('data/ld_regions.tsv', sep='\t')
relevant_ancestries = np.isin(ld_regions['pop'], studies_to_process['ancestry'].unique())
ld_regions = ld_regions[relevant_ancestries]

extracted_studies = [s["extracted_location"] for i,s in studies_to_process.iterrows()]
extracted_study_pattern = '{study_location}extracted_snps.tsv'

imputation_pattern = LD_BLOCK_DATA_DIR + '{ld_block}/imputation_complete'
finemapping_pattern = LD_BLOCK_DATA_DIR + '{ld_block}/finemapping_complete'
ld_blocks = [f'{ld["pop"]}/{ld.chr}/{ld.start}_{ld.stop}' for i, ld in ld_regions.iterrows()]

ld_block_matrices = [f'{LD_BLOCK_MATRICES_DIR}{ld["pop"]}/{ld.chr}_{ld.start}_{ld.stop}' for i, ld in ld_regions.iterrows()]
ld_blocks_lookup = [f'{LD_BLOCK_DATA_DIR}{ld["pop"]}/{ld.chr}/{ld.start}_{ld.stop}' for i, ld in ld_regions.iterrows()]
ld_block_matrices = dict(zip(ld_blocks_lookup, ld_block_matrices))

#TODO: these ld matrices has NaNs for every line of the .ld file, skipping for now
#ld_blocks = ld_blocks[0::50]

### OUTPUT DATA FILES
studies_processed_file = RESULTS_DIR + 'studies_processed.tsv'
ld_blocks_to_process = f'{PIPELINE_METADATA}updated_ld_blocks_to_colocalise.tsv'
coloc_pattern = LD_BLOCK_RESULTS_DIR + '{ld_block}/hyprcoloc_results_' + TIMESTAMP + '.tsv'
coloc_results = f'{RESULTS_DIR}{TIMESTAMP}/coloc_results.tsv'
all_study_regions = f'{RESULTS_DIR}{TIMESTAMP}/all_study_regions.tsv'
results_metadata = f'{RESULTS_DIR}{TIMESTAMP}/results_metadata.tsv'

rule all:
    input: expand(extracted_study_pattern, study_location=extracted_studies),
        ld_blocks_to_process,
        expand(imputation_pattern, ld_block=ld_blocks),
        expand(finemapping_pattern, ld_block=ld_blocks),
        expand(coloc_pattern, ld_block=ld_blocks),
        coloc_results,
        all_study_regions,
        results_metadata

rule extract_regions_from_studies:
    params: lambda wildcards: list(filter(bool, wildcards.study_location.split("/")))[-1]
    output: extracted_study_pattern
    threads: 1
    run:
        study = studies_to_process[studies_to_process.study_name == str(params)].values.flatten().tolist()
        #TODO: this assignment is hacky and prone to breaking if you change the tsv.  change it to be more explicit
        script = study[-1]
        command = [script] + study[2:-1]
        command = [str(c) for c in command]
        subprocess.run(command)

rule organise_extracted_studies_into_ld_regions:
    input: expand(extracted_study_pattern, study_location=extracted_studies)
    output: temporary(ld_blocks_to_process)
    threads: 1
    shell:
        """
        Rscript organise_extracted_regions_into_ld_regions.R --output_file {output}
        """

rule impute_per_ld_region:
    input: ld_blocks_to_process
    output: temporary(imputation_pattern)
    threads: 12
    params:
        ld_dir=lambda wildcards, output: os.path.dirname(output[0])
    run:
        ld_blocks = pd.read_csv(ld_blocks_to_process, sep='\t')
        ld_block = ld_blocks[ld_blocks.data_dir == params.ld_dir]
        env_vars = "export LD_PRELOAD= && export OMP_NUM_THREADS=16 && export MKL_NUM_THREADS=16 && NUMEXPR_NUM_THREADS=16"

        if len(ld_block) == 0:
            command = f"mkdir -p $(dirname {output}) && touch {output}"
        else:
            command = f"{env_vars} && python3 standardise_and_impute_region.py \
                --ld_region_prefix {ld_block.iloc[0]['region_prefix']} \
                --ld_block_dir {ld_block.iloc[0]['data_dir']}"
        subprocess.run(command, shell=True)


rule finemap_per_ld_region:
    input: ld_blocks_to_process, imputation_pattern
    output: temporary(finemapping_pattern)
    threads: 1
    params:
        ld_dir=lambda wildcards, output: os.path.dirname(output[0])
    run:
        ld_blocks = pd.read_csv(ld_blocks_to_process, sep='\t')
        ld_block = ld_blocks[ld_blocks.data_dir == params.ld_dir]

        if len(ld_block) == 0:
            command = f"mkdir -p $(dirname {output}) && touch {output}"
        else:
            command = f"Rscript finemap_extracted_regions.R \
                --ld_region_prefix {ld_block.iloc[0]['region_prefix']} \
                --ld_block_dir {ld_block.iloc[0]['data_dir']}"
        subprocess.run(command, shell=True)

rule colocalise_per_ld_region:
    input:
        ld_block = ld_blocks_to_process,
        finemap = finemapping_pattern
    output: coloc_pattern
    run:
        ld_dir = os.path.dirname(input.finemap)
        ld_block_matrix = ld_block_matrices[ld_dir]

        command = f"Rscript colocalise_studies_per_ld_block.R \
            --ld_region_prefix {ld_block_matrix} \
            --ld_block_dir {ld_dir} \
            --coloc_result_file {output}"
        subprocess.run(command, shell=True)

rule compile_results:
    input:
        all_coloc_results = expand(coloc_pattern, ld_block=ld_blocks)
    output:
        coloc_results = coloc_results,
        all_study_regions = all_study_regions,
        results_metadata = results_metadata
    shell:
       """
       mkdir -p $(dirname {output})
       Rscript compile_results.R \
           --studies_to_process {studies_to_process_file} \
           --studies_processed {studies_processed_file} \
           --coloc_input_files {input.all_coloc_results} \
           --all_study_regions_file {output.all_study_regions} \
           --coloc_results_file {output.coloc_results} \
           --compiled_results_metadata_file {output.results_metadata}
       """

# rule perform_mr_analysis:
#     input: expand(coloc_pattern, ld_block=ld_blocks),
#     output: list()
#     shell:
#         """
#         Rscript perform_mr_analysis.R
#         """


onsuccess:
    print('Print important files to investigate here')

onerror:
    print(':(')
