name: CI/CD

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check that tests have been run successfully
      env:
        BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
      run: |
        if [ ! -f tests/testing_complete.txt ]; then
          echo "Tests have not been run successfully,  please run Rscript tests/testthat/run_tests.R and commit the results"
          exit 1
        fi
        if ! grep -q "$BRANCH_NAME" tests/testing_complete.txt; then
          echo "Tests have not been run successfully for branch: $BRANCH_NAME, please run Rscript tests/testthat/run_tests.R and commit the results"
          exit 1
        fi

  build:
    runs-on: ubuntu-latest
    # if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v2
    - name: Set up SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.ORACLE_SSH_PRIVATE_KEY }}" > ~/.ssh/oracle_gpmap.key
        chmod 600 ~/.ssh/oracle_gpmap.key
        ssh-keyscan -H "${{ secrets.ORACLE_SERVER }}" >> ~/.ssh/known_hosts

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push API image
      uses: docker/build-push-action@v2
      with:
        file: docker/Dockerfile
        context: .
        push: true
        tags: |
          mrcieu/genotype-phenotype-map:latest
          mrcieu/genotype-phenotype-map:${{ github.sha }}
        cache-from: type=registry,ref=mrcieu/genotype-phenotype-map:latest
        cache-to: type=inline

    - name: Populate .env files and copy deployment files to server
      env:
        ORACLE_SERVER: ${{ secrets.ORACLE_SERVER }}
      run: |
        FILES=".env.pipeline_worker"
        scp -i ~/.ssh/oracle_gpmap.key $FILES opc@${ORACLE_SERVER}:/home/opc/genotype-phenotype-api/
